### PR TITLE
-list improvements

### PR DESCRIPTION
**Pull request by benprew**
* make -list show archives with # of snapshots
* add tests
* organize the archive by url instead of title

### CODE REVIEW

**Comment by benprew** [comment]
Here's what the list output looks like now:

```
><> ./stashbox -list
Archive listing...
1. github.com/SebastiaanKlippert/go-wkhtmltopdf [1 image(s)]
2. github.com/benprew/clippy [1 image(s)]
3. github.com/benprew/pony [3 image(s)]
4. github.com/bmatcuk/doublestar [1 image(s)]
5. norvig.com/sudoku.html [1 image(s)]
6. www.yahoo.com [1 image(s)]
```

And the -open flag opens the most recent snapshot of an archive (specify a number from the -list command).  I don't have a windows machine, so I couldn't test if the windows command, which is just listing the file actually opens the file.  From my searching, that _should_ work, but it hasn't been tested.

Let me know if there are any changes you'd like to see to this PR.

Thanks

**Comment by zpeters** [comment]
Would it be possible to break up this PR a bit into one for the list command and one for the open command. Everthing in the list looks good and i'd like to merge that, but some code from the open code is throwing an error with "Gosec", i'd like to review that a bit more.

Thanks again for contributing. This is awesome

**Comment by benprew** [comment]
No problem, happy to break it up into separate PRs, I did feel like it was
getting a little large as I was adding the "open" command.

Thanks

**Comment by benprew** [comment]
Ok, this is now the PR for just the changes to the list command.  I'll create a separate PR for the open command.

Thanks!

**Comment by zpeters** [comment]
Excellent.  Thank you for contributing. I really appreciate it

**Pull request merged**
